#!/usr/bin/env perl

# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2016 Software Assurance Marketplace

#** @file testcsa_agent
# @brief A fake csa_agent that merely tells the AgentMonitor that a job started.

use 5.010;
use utf8;
use warnings;
use strict;

use Getopt::Long qw/GetOptions/;
use Pod::Usage qw/pod2usage/;
use English '-no_match_vars';
use Carp 'croak';
use Log::Log4perl;
use Log::Log4perl::Level;

use SWAMP::Client::AgentClient qw( csaAgentFinished );
use SWAMP::SWAMPUtils qw( loadProperties getLoggingConfigString );
my $help = 0;
my $man  = 0;
my $debug = 0;
my $bogfile;
our $VERSION = '0.00';

GetOptions(
    'bog=s' => \$bogfile,
    'debug' => \$debug,
    'help|?' => \$help,
    'man'    => \$man,
) or pod2usage(2);

sub logtag {
    return $PROGRAM_NAME;
}
sub logfilename {
    return "${PROGRAM_NAME}.log";
}
Log::Log4perl->init( getLoggingConfigString() );
my $log = Log::Log4perl->get_logger(q{});
$log->level($debug ? $TRACE : $INFO);

if ($help) { pod2usage(1); }
if ($man) { pod2usage( '-verbose' => 2 ); }
my %bog;
if (loadProperties($bogfile , \%bog) > 0) {
    $bog{'clusterid'} = 'testmode';
    csaAgentFinished(\%bog);
}

__END__
=pod

=encoding utf8

=head1 NAME


=head1 SYNOPSIS



=head1 DESCRIPTION

=head1 OPTIONS

=over 8

=item --man

Show manual page for this script

=back

=head1 EXAMPLES

=head1 SEE ALSO

=cut
