#!/bin/bash

# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2016 Software Assurance Marketplace

if [ `uname` = 'Darwin' ]
then 
    lib=-Ilib
fi
cd /opt/swamp/run
perl $lib /opt/swamp/bin/csa_agent.pl $*
