#!/bin/bash

# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2016 Software Assurance Marketplace

export PATH=/usr/bin:/usr/local/bin:/bin
export PERLBREW_ROOT=/opt/perl5
export PERLBREW_HOME=/tmp/.perl5
source $PERLBREW_ROOT/etc/bashrc
perlbrew use perl-5.18.1
sudo /opt/perl5/perls/perl-5.18.1/bin/perl -I/opt/swamp/perl5 /opt/swamp/bin/DomainMonitor.pl $*
