#!/usr/bin/env perl 

# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2016 Software Assurance Marketplace

#** @file vm_masterinfo
# 
# @brief 
# @author Dave Boulineau (db), dboulineau@continuousassurance.org
# @date 09/23/2014 07:53:06
#*

use 5.010;
use utf8;
use warnings;
use strict;
use FindBin qw($Bin);
use lib ( "$FindBin::Bin/../perl5", "$FindBin::Bin/lib" );

use Getopt::Long qw/GetOptions/;
use Pod::Usage qw/pod2usage/;
use English '-no_match_vars';
use Carp qw(carp croak);

use VMTools qw(
consoleMsg errorMsg init logMsg pkgshutdown 
inspectmaster
startVM
defineVM
listMasters
listVMs
initProjectLog
createImages
createXML
vmVNCDisplay
vmExists
vmState);
use VMConstants;

my $help = 0;
my $man  = 0;
my $list = 0;
my $fullnames = 0;
my $mastername;
our $VERSION = '0.00';

GetOptions(
    'help|?' => \$help,
    'list' => \$list,
    'full' => \$fullnames,
    'inspect=s' => \$mastername,
    'man'    => \$man,
) or pod2usage(2);

if ($help) { pod2usage(1); }
if ($man) { pod2usage( '-verbose' => 2 ); }

if ($list || $fullnames) {
    my @list = listMasters($fullnames);
    foreach (sort @list) {
        print "$_\n";
    }
    exit 0;
}
if ($mastername) {
    print inspectmaster($mastername);
}

__END__
=pod

=encoding utf8

=head1 NAME

vm_masterinfo -- Run virt-inspect2 on a master image

=head1 SYNOPSIS

vm_masterinfo [--list] [--full] [--inspect mastername]

=head1 DESCRIPTION

The vm_masterinfo script will display, to standard out, the packages installed
on a VM image as an xml file. See virt-inspect2 for details of what is shown.

=head1 OPTIONS

=over 8

=item --list 

Show the list of master names, this is the same output that start_vm --list will display.

=item --full

Show the full list of all master names, including all revisions of a master
image. The difference between --list and --full is that --list only
shows a single version for each available master, --full shows all versions of all masters.

=item --inspect B<mastername>

Display information about B<mastername>. B<mastername> can be either a short
name taken from the --list option or a full name taken from the --full option.

=item --man

Show manual page for this script

=back

=head1 EXAMPLES

sudo vm_masterinfo --full

sudo vm_masterinfo --inspect condor-fedora-19.0-64-master-2013083001.qcow2

sudo vm_masterinfo --list

sudo vm_masterinfo --inspect fedora-19.0-64

=cut


